swagger: "2.0"
info:
  description: "Backend REST API using Node, Express, Sequelize and MySql with Spotify API"
  version: "1.0.1"
  title: "🎹 UMG Spotify Track REST API 🎹"
  
servers:
  - url: https://api.umg.codes/v1/api
    description: Optional server description, e.g. Main (production) server
  - url: https://api.umg.codes/v1/api
    description: Optional server description, e.g. Internal staging server for testing

schemes: 
  - http
  - https

host: 
  - localhost:7001

basePath: "/v1/api/isrc"

paths:
  /artists:
    get:
      summary: "Search for artists by Spotify ID or query string"
      description: "Get one artist by Spotify ID or  Get all artist by name matching a query string"
      produces:
        - "application/json"
      parameters:
      responses:
        200:
          description: 200 Success
          schema:
            type: array
            items:
        500:
          description: 500 Internal Server Error
          schema:
            type: object
            items:
    
  /tracks/{isrcId}:
    get:
      summary: "Get track record"
      description: "Get a track record using ISRC code"
      produces:
        - "application/json"
      parameters:
      responses:
        200:
          description: 200 Success
          schema:
            type: object
            items:
        500:
          description: 500 Internal Server Error
          schema:
            type: object
            items:
    post:
      summary: "Create track record"
      description: "Update a track record using ISRC code""
      produces:
        - "application/json"
      parameters:
      responses:
        200:
          description: 200 Success
          schema:
            type: object
            items:
        500:
          description: 500 Internal Server Error
          schema:
            type: object
            items:
    